version: '3.8'
services: 
        authentication:
                image: sajadkh/doctor_system_authentication
                ports:
                        - 8000:8000
                networks:
                        - doctor-net
                deploy:
                        replicas: 2
        patient_panel:
                image: sajadkh/doctor_system_patient_panel
                ports:
                        - 8002:8002
                networks:
                        - doctor-net
                depends_on:
                        - authentication
                deploy:
                         replicas: 1
        doctor_panel:
                image: sajadkh/doctor_system_doctor_panel
                ports:
                        - 8001:8001
                networks:
                        - doctor-net
                depends_on:
                        - authentication
                deploy:
                         replicas: 1
networks:
        doctor-net:
        
